import First from "../../assets/images/ceremony/DSC00451.jpg";
import Second from "../../assets/images/ceremony/DSC00429.jpg";
import Third from "../../assets/images/ceremony/DSC00396.jpg";
// import Third from "../../assets/DSC00717.jpg";

let prefix = "https://github.com/maxgrier/WeddingPhotos/blob/main/src/assets/ceremony/new/"
let postfix = "?raw=true"


export default [
  {
    title: "First Slide",
    description: "This is the first slider Image of our carousel",
    urls: First,
    layout: "landscape",
    name: "DSC00045.jpg",
    name2: "DSC00045",
  },
  {
    title: "Second Slide",
    description: "This is the second slider Image of our carousel",
    urls: Second,
    layout: "portriat",
    name: "DSC00429.jpg",
    name2: "DSC00429",
  },
  {
    title: "Second Slide",
    description: "This is the second slider Image of our carousel",
    urls: Third,
    layout: "portriat",
    name: "DSC00396.jpg",
    name2: "DSC00396",
  },
  {
    // urls: require("../../assets/images/ceremony/new/DSC00468.jpg"),
    urls: prefix + "DSC00468.jpg" + postfix,
    layout: "portriat",
    name: "DSC00468.jpg",
    name2: "DSC00468",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC00474.jpg"),
    layout: "portriat",
    name: "DSC00474.jpg",
    name2: "DSC00474",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC00676.jpg"),
    layout: "portriat",
    name: "DSC00676.jpg",
    name2: "DSC00676",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC00710.jpg"),
    layout: "portriat",
    name: "DSC00710.jpg",
    name2: "DSC00710",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC00716.jpg"),
    layout: "portriat",
    name: "DSC00716.jpg",
    name2: "DSC00716",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04796.jpg"),
    layout: "portriat",
    name: "DSC04796.jpg",
    name2: "DSC04796",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04800.jpg"),
    layout: "portriat",
    name: "DSC04800.jpg",
    name2: "DSC04800",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04808.jpg"),
    layout: "portriat",
    name: "DSC04808.jpg",
    name2: "DSC04808",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04814.jpg"),
    layout: "portriat",
    name: "DSC04814.jpg",
    name2: "DSC04814",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04816.jpg"),
    layout: "portriat",
    name: "DSC04816.jpg",
    name2: "DSC04816",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04819.jpg"),
    layout: "portriat",
    name: "DSC04819.jpg",
    name2: "DSC04819",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04821.jpg"),
    layout: "portriat",
    name: "DSC04821.jpg",
    name2: "DSC04821",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04825.jpg"),
    layout: "portriat",
    name: "DSC04825.jpg",
    name2: "DSC04825",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04831.jpg"),
    layout: "portriat",
    name: "DSC04831.jpg",
    name2: "DSC04831",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04835.jpg"),
    layout: "portriat",
    name: "DSC04835.jpg",
    name2: "DSC04835",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04838.jpg"),
    layout: "portriat",
    name: "DSC04838.jpg",
    name2: "DSC04838",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04844.jpg"),
    layout: "portriat",
    name: "DSC04844.jpg",
    name2: "DSC04844",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04854.jpg"),
    layout: "portriat",
    name: "DSC04854.jpg",
    name2: "DSC04854",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04855.jpg"),
    layout: "portriat",
    name: "DSC04855.jpg",
    name2: "DSC04855",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04858.jpg"),
    layout: "portriat",
    name: "DSC04858.jpg",
    name2: "DSC04858",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04863.jpg"),
    layout: "portriat",
    name: "DSC04863.jpg",
    name2: "DSC04863",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04871.jpg"),
    layout: "portriat",
    name: "DSC04871.jpg",
    name2: "DSC04871",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04878.jpg"),
    layout: "portriat",
    name: "DSC04878.jpg",
    name2: "DSC04878",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04880.jpg"),
    layout: "portriat",
    name: "DSC04880.jpg",
    name2: "DSC04880",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04882.jpg"),
    layout: "portriat",
    name: "DSC04882.jpg",
    name2: "DSC04882",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04898.jpg"),
    layout: "portriat",
    name: "DSC04898.jpg",
    name2: "DSC04898",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04902.jpg"),
    layout: "portriat",
    name: "DSC04902.jpg",
    name2: "DSC04902",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04909.jpg"),
    layout: "landscape",
    name: "DSC04909.jpg",
    name2: "DSC04909",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04915.jpg"),
    layout: "portriat",
    name: "DSC04915.jpg",
    name2: "DSC04915",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04918.jpg"),
    layout: "portriat",
    name: "DSC04918.jpg",
    name2: "DSC04918",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04929.jpg"),
    layout: "landscape",
    name: "DSC04929.jpg",
    name2: "DSC04929",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04932.jpg"),
    layout: "landscape",
    name: "DSC04932.jpg",
    name2: "DSC04932",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04934.jpg"),
    layout: "portriat",
    name: "DSC04934.jpg",
    name2: "DSC04934",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04936.jpg"),
    layout: "portriat",
    name: "DSC04936.jpg",
    name2: "DSC04936",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04959.jpg"),
    layout: "portriat",
    name: "DSC04959.jpg",
    name2: "DSC04959",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC04960.jpg"),
    layout: "portriat",
    name: "DSC04960.jpg",
    name2: "DSC04960",
  },
  {
    urls: require("../../assets/images/ceremony/new/DSC00676.jpg"),
    urls: "https://github.com/maxgrier/WeddingPhotos/blob/main/src/assets/DSC00676.jpg?raw=true",
    layout: "portriat",
    name: "DSC00676.jpg",
    name2: "DSC00676",
  },
  // {
  //   urls: require("../../assets/images/ceremony/new/DSC04963.jpg"),
  //   layout: "portriat",
  //   name: "DSC04963.jpg",
  //   name2: "DSC04963",
  // },
];
