import First from "../../assets/images/portraits/DSC00045.jpg";
import Second from "../../assets/images/portraits/DSC00126.jpg";
import Third from "../../assets/images/portraits//new/DSC00013.jpg";
// import Third from "../../assets/DSC00717.jpg";

export default [
  {
    title: "First Slide",
    description: "This is the first slider Image of our carousel",
    urls: First,
    layout: 'portriat',
    name: "DSC00045.jpg",
    name2: "DSC00045",
  },
  {
    title: "Second Slide",
    description: "This is the second slider Image of our carousel",
    urls: Second,
    layout: 'portriat',
    name: "DSC00126.jpg",
    name2: "DSC00126",
  },
  {
    title: "Third Slide",
    description: "This is the second slider Image of our carousel",
    urls: Third,
    layout: 'portriat',
    name: "DSC00013.jpg",
    name2: "DSC00013",
  },
  {
    title: "",
    description: "",
    urls: require("../../assets/images/portraits/new/DSC00056.jpg"),
    layout: 'portriat',
    name: "DSC00056.jpg",
    name2: "DSC00056",
  },
  {
    title: "",
    description: "",
    urls: require("../../assets/images/portraits/new/DSC00060.jpg"),
    layout: 'portriat',
    name: "DSC00060.jpg",
    name2: "DSC00060",
  },
  {
    title: "",
    description: "",
    urls: require("../../assets/images/portraits/new/DSC00140.jpg"),
    layout: 'portriat',
    name: "DSC00140.jpg",
    name2: "DSC00140",
  },
  {
    title: "",
    description: "",
    urls: require("../../assets/images/portraits/new/DSC00145.jpg"),
    layout: 'portriat',
    name: "DSC00145.jpg",
    name2: "DSC00145",
  },
  {
    title: "",
    description: "",
    urls: require("../../assets/images/portraits/new/DSC00149.jpg"),
    layout: 'portriat',
    name: "DSC00149.jpg",
    name2: "DSC00149",
  },
  {
    title: "",
    description: "",
    urls: require("../../assets/images/portraits/new/DSC00156.jpg"),
    layout: 'portriat',
    name: "DSC00156.jpg",
    name2: "DSC00156",
  },
  {
    title: "",
    description: "",
    urls: require("../../assets/images/portraits/new/DSC00158.jpg"),
    layout: 'portriat',
    name: "DSC00158.jpg",
    name2: "DSC00158",
  },
  {
    title: "",
    description: "",
    urls: require("../../assets/images/portraits/new/DSC00159.jpg"),
    layout: 'portriat',
    name: "DSC00159.jpg",
    name2: "DSC00159",
  },
  // {
  //   title: "",
  //   description: "",
  //   urls: Second,
  //   layout: 'portriat',
  //   name: "DSC00056.jpg",
  //   name2: "DSC00056",
  // },
  // {
  //   title: "Third Slide",
  //   description: "This is the Third slider Image of our carousel",
  //   urls: Third,
  //   name: "DSC00717.jpg",
  //   name2: "DSC00717",
  // },
  // {
  //   title: "Fourth Slide",
  //   description: "This is the Fourth slider Image of our carousel",
  //   urls: "https://mdbootstrap.com/img/Photos/Slides/img%20(133).jpg",
  // },
  // {
  //   title: "Fifth Slide",
  //   description: "This is the Fifth slider Image of our carousel",
  //   urls: "https://mdbootstrap.com/img/Photos/Slides/img%20(147).jpg",
  // },
  // {
  //   title: "Sixth Slide",
  //   description: "This is the Sixth slider Image of our carousel",
  //   urls: "https://mdbootstrap.com/img/Photos/Slides/img%20(105).jpg",
  // },
  // {
  //   title: "Seventh Slide",
  //   description: "This is the Seventh slider Image of our carousel",
  //   urls: "https://mdbootstrap.com/img/Photos/Slides/img%20(102).jpg",
  // },
];